`NumPy` is the fundamental package for `scientific computing` in Python. NumPy arrays facilitate `advanced mathematical and other types of operations` on `large numbers of data`. Typically, such operations are executed more `efficiently and with less code` than is possible using Python’s built-in sequences. NumPy is not another programming language but a Python `extension module`. It provides `fast and efficient` operations on arrays of `homogeneous data`.

Advantages of using Numpy Arrays Over Python Lists:

* consumes less memory. <br>
* fast as compared to the python List. <br>
* convenient to use. <br>

Faster?? by how much?

<img src="comparison.png" style="background-color:white;" />

In [ ]:
!pip install numpy

In [2]:
import numpy as np

Numpy is a class, just like any other class in python like str, int

But we never import str, int then why this?

It is not predefined class like you have defined classes earlier, same somebody else defined this class hence we need to import it

## Single dimension list

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
np.array([1,2])

array([1, 2])

In [5]:
# check type of Numpy Array
print(type(a))

<class 'numpy.ndarray'>


Multi dimension list

In [6]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)

[[1 2 3]
 [4 5 6]]


Wanna compare python list vs numpy array by yourself

In [7]:
# importing system module
import sys
  
# declaring a list of 1000 elements 
S = range(1000)
  
# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(S))
  
# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
  
# declaring a Numpy array of 1000 elements 
D = np.array(S)
  
# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
  
# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  4
Size of the whole Numpy array in bytes:  4000


Lets start exploring about numpy functionality

## Indexing

In [8]:
a = np.array([1, 5, 3])
print(a[:-1])

[1 5]


In [9]:
a = np.array([[10, 20, 30], (40, 50, 60)])
print(a)

[[10 20 30]
 [40 50 60]]


How it is getting stored

```python
np.array([
#cols ->     0   1   2
          0 [10, 20, 30], 
          1 [40, 50, 60],
#    rows ^
])
```

In [10]:
a[0, 1]

20

In [11]:
# a[row, col]
a[0, 1]

20

In [12]:
a[1, 0]

40

In [13]:
a[1, 0] + a[0, 1]

60

In [14]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
a[0, -1]

30

In [16]:
a[-1, -1]

60

In [17]:
a[:-2]

array([], shape=(0, 3), dtype=int32)

## Slicing

In [18]:
#               0, 1, 2, 3, 4, 5, 6
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1 : 5])

[2 3 4 5]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#               0  1  2  3  4  5  6

print(arr[1 : 5 : 2]) #1,2,3,4 
# 1 + 2 + 2
# 1, 3

[2 4]


In [20]:
#  if it is a 2-d array
arr = np.array([
#    0, 1, 2, 3, 4
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10]
])

arr[0:2, 2]

array([3, 8])

In [21]:
print(arr[0:1, 1:3])

[[2 3]]


In [22]:
print(arr[1:1, 1:3])

[]


In [23]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [24]:
arr = np.array([
    [1,2,3,4,5,6],
    [6,7,8,9,10,11]
    
])

print(arr[4:100,2:4])

[]


## Data types in np

* i - integer

* b - boolean

* u - unsigned integer

* f - float

* c - complex float

* m - timedelta

* M - datetime

* O - object

* S - string

* U - unicode string

* V - fixed chunk of memory for other type ( void )


In [25]:
arr = np.array([1, 2])
print(arr.dtype)

int32


In [26]:
arr = np.array(['name', '2'])
print(arr.dtype)

<U4


In [30]:
arr = np.array(['hitesh', 'panchal'])
print(arr.dtype)

<U7


In [31]:
arr = np.array([0, 1])
print(arr.dtype)

int32


In [32]:
arr = np.array([0.0, 1.1])
print(arr.dtype)

float64


In [33]:
arr = np.array([1, 2], dtype="U")
print(arr)
print(arr.dtype)

['1' '2']
<U1


In [34]:
arr = np.array([111, 0, 3])

newarr = arr.astype(str)

print(newarr)
print(newarr.dtype)

['111' '0' '3']
<U11


In [35]:
arr = np.array([1.9, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [36]:
np.array([1.9, 2.1, 3.1], dtype="int")

array([1, 2, 3])

## Shape

(How many `rows`, how many `columns`)

In [37]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [38]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# ndim

Number of array dimensions.

In [39]:
print(np.array(8).ndim)

0


In [40]:
print(np.array([8, 1]).ndim)

1


In [41]:
print(np.array([8, 1, 2]).ndim)

1


In [43]:
print(np.array([[8, 2, 1], [9, 2, 3]]).ndim)

2


## Reshape

In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Lets reverse everything

In [47]:
# [ 1  2  3  4  5  6  7  8  9 10 11 12]
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [48]:
arr = newarr.reshape(12)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [49]:
arr = newarr.reshape(-1)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [50]:
# [[[ 1  2  3]
#   [ 4  5  6]]

#  [[ 7  8  9]
#   [10 11 12]]]

print(newarr.reshape(2, 2, -1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Iterating Arrays

In [51]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [53]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [54]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [55]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [56]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [57]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [58]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## Append

In [59]:
arr = np.array([1,2,3])
np.append(arr, [1])

array([1, 2, 3, 1])

In [60]:
arr = np.array([[1,2,3], [2,3,4]])
np.append(arr, [1])

array([1, 2, 3, 2, 3, 4, 1])

In [61]:
arr = np.array([[1,2,3], [2,3,4]])
np.append(arr, [[5,6,7]], axis=0)

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [62]:
arr = np.array([[1,2,3], [2,3,4]])
print(arr.shape)
print(np.array([[5],[6]]).shape)
np.append(arr, [[5],[6]], axis=1)

(2, 3)
(2, 1)


array([[1, 2, 3, 5],
       [2, 3, 4, 6]])

## Stack

In [63]:
arrays = [np.random.randn(5) for _ in range(10)]
arrays

[array([-0.52080709, -0.15136883, -2.15819016, -0.14570637,  0.54671092]),
 array([-0.61494489,  0.34358773,  0.88003603, -1.08156501,  1.32187857]),
 array([-0.51356577, -0.44115561, -0.46678351,  0.30288594,  2.03856688]),
 array([ 0.91687385, -0.58835036, -0.99912557, -0.47296926,  0.40578114]),
 array([-2.01465172,  1.46590919,  1.48781372,  0.50803456,  0.23536589]),
 array([-0.62468998,  0.0506514 ,  0.01914159,  1.2100571 ,  0.33907303]),
 array([ 0.23475903,  1.07041889, -0.09744266,  2.18088051, -0.5565556 ]),
 array([ 1.56555595, -0.45939919, -0.44554255,  0.4180463 ,  0.41326966]),
 array([ 1.83047387,  0.26109834,  0.39193675, -1.62934534, -0.47608355]),
 array([-0.69291805,  0.01007997,  0.06262497, -0.41769496, -0.34149574])]

In [64]:
print(np.stack(arrays, axis=0).shape)
np.stack(arrays, axis=0)

(10, 5)


array([[-0.52080709, -0.15136883, -2.15819016, -0.14570637,  0.54671092],
       [-0.61494489,  0.34358773,  0.88003603, -1.08156501,  1.32187857],
       [-0.51356577, -0.44115561, -0.46678351,  0.30288594,  2.03856688],
       [ 0.91687385, -0.58835036, -0.99912557, -0.47296926,  0.40578114],
       [-2.01465172,  1.46590919,  1.48781372,  0.50803456,  0.23536589],
       [-0.62468998,  0.0506514 ,  0.01914159,  1.2100571 ,  0.33907303],
       [ 0.23475903,  1.07041889, -0.09744266,  2.18088051, -0.5565556 ],
       [ 1.56555595, -0.45939919, -0.44554255,  0.4180463 ,  0.41326966],
       [ 1.83047387,  0.26109834,  0.39193675, -1.62934534, -0.47608355],
       [-0.69291805,  0.01007997,  0.06262497, -0.41769496, -0.34149574]])

In [65]:
print(np.stack(arrays, axis=1).shape)
np.stack(arrays, axis=1)

(5, 10)


array([[-0.52080709, -0.61494489, -0.51356577,  0.91687385, -2.01465172,
        -0.62468998,  0.23475903,  1.56555595,  1.83047387, -0.69291805],
       [-0.15136883,  0.34358773, -0.44115561, -0.58835036,  1.46590919,
         0.0506514 ,  1.07041889, -0.45939919,  0.26109834,  0.01007997],
       [-2.15819016,  0.88003603, -0.46678351, -0.99912557,  1.48781372,
         0.01914159, -0.09744266, -0.44554255,  0.39193675,  0.06262497],
       [-0.14570637, -1.08156501,  0.30288594, -0.47296926,  0.50803456,
         1.2100571 ,  2.18088051,  0.4180463 , -1.62934534, -0.41769496],
       [ 0.54671092,  1.32187857,  2.03856688,  0.40578114,  0.23536589,
         0.33907303, -0.5565556 ,  0.41326966, -0.47608355, -0.34149574]])

Multi-dimensional array

In [66]:
arrays = [np.random.randn(3,5) for _ in range(10)]
arrays

[array([[-1.18900254,  0.63435298, -0.22967496,  0.40804783, -0.02191917],
        [-0.64138398,  0.6297736 , -0.88818304, -0.26935647,  0.58866686],
        [ 0.38682788, -0.47176892, -0.09449444, -0.56756877, -0.3765066 ]]),
 array([[ 0.60939773,  1.72843818,  0.27160744, -0.07489704, -0.31836805],
        [-2.0899181 ,  0.93588396,  0.47399004, -0.66509912,  0.15298177],
        [ 0.89922064, -1.33736273, -0.59715444,  2.60511151,  0.97870795]]),
 array([[ 1.59018528, -1.19023725,  1.49812731,  1.21247899,  1.15652777],
        [-1.29140263, -0.59121266, -1.04945414,  0.02143987,  0.73580364],
        [ 1.16117905,  0.35318962,  0.87906858, -1.64815505,  0.44481838]]),
 array([[-0.69140471, -1.94444543,  1.03297209,  0.52767843, -1.06761744],
        [ 0.96852732,  0.50064276, -0.50251532,  0.32234854, -0.15647841],
        [ 0.68071956,  0.97014045, -0.54982036, -0.84193837, -0.75311422]]),
 array([[ 2.26658124, -0.19734964,  0.69949169, -0.00648389,  1.601222  ],
        [ 0.14364

In [67]:
print(np.stack(arrays, axis=0).shape)
np.stack(arrays, axis=0)

(10, 3, 5)


array([[[-1.18900254,  0.63435298, -0.22967496,  0.40804783,
         -0.02191917],
        [-0.64138398,  0.6297736 , -0.88818304, -0.26935647,
          0.58866686],
        [ 0.38682788, -0.47176892, -0.09449444, -0.56756877,
         -0.3765066 ]],

       [[ 0.60939773,  1.72843818,  0.27160744, -0.07489704,
         -0.31836805],
        [-2.0899181 ,  0.93588396,  0.47399004, -0.66509912,
          0.15298177],
        [ 0.89922064, -1.33736273, -0.59715444,  2.60511151,
          0.97870795]],

       [[ 1.59018528, -1.19023725,  1.49812731,  1.21247899,
          1.15652777],
        [-1.29140263, -0.59121266, -1.04945414,  0.02143987,
          0.73580364],
        [ 1.16117905,  0.35318962,  0.87906858, -1.64815505,
          0.44481838]],

       [[-0.69140471, -1.94444543,  1.03297209,  0.52767843,
         -1.06761744],
        [ 0.96852732,  0.50064276, -0.50251532,  0.32234854,
         -0.15647841],
        [ 0.68071956,  0.97014045, -0.54982036, -0.84193837,
         

In [68]:
print(np.stack(arrays, axis=1).shape)
np.stack(arrays, axis=1)

(3, 10, 5)


array([[[-1.18900254,  0.63435298, -0.22967496,  0.40804783,
         -0.02191917],
        [ 0.60939773,  1.72843818,  0.27160744, -0.07489704,
         -0.31836805],
        [ 1.59018528, -1.19023725,  1.49812731,  1.21247899,
          1.15652777],
        [-0.69140471, -1.94444543,  1.03297209,  0.52767843,
         -1.06761744],
        [ 2.26658124, -0.19734964,  0.69949169, -0.00648389,
          1.601222  ],
        [-1.0416231 ,  1.53004749,  0.62399482,  0.06753822,
         -1.07268787],
        [ 1.55013317,  0.41007045, -2.02611301, -1.69483868,
          0.05174977],
        [-0.48537537, -0.2458134 , -1.16636264, -0.94563124,
          1.47767338],
        [ 1.02654808, -0.30091342, -0.72221617,  0.33062487,
         -0.38524091],
        [ 0.20456734,  0.68352191, -0.36749846, -1.67479157,
         -0.93645234]],

       [[-0.64138398,  0.6297736 , -0.88818304, -0.26935647,
          0.58866686],
        [-2.0899181 ,  0.93588396,  0.47399004, -0.66509912,
          0.1

In [69]:
print(np.stack(arrays, axis=2).shape)
np.stack(arrays, axis=2)

(3, 5, 10)


array([[[-1.18900254,  0.60939773,  1.59018528, -0.69140471,
          2.26658124, -1.0416231 ,  1.55013317, -0.48537537,
          1.02654808,  0.20456734],
        [ 0.63435298,  1.72843818, -1.19023725, -1.94444543,
         -0.19734964,  1.53004749,  0.41007045, -0.2458134 ,
         -0.30091342,  0.68352191],
        [-0.22967496,  0.27160744,  1.49812731,  1.03297209,
          0.69949169,  0.62399482, -2.02611301, -1.16636264,
         -0.72221617, -0.36749846],
        [ 0.40804783, -0.07489704,  1.21247899,  0.52767843,
         -0.00648389,  0.06753822, -1.69483868, -0.94563124,
          0.33062487, -1.67479157],
        [-0.02191917, -0.31836805,  1.15652777, -1.06761744,
          1.601222  , -1.07268787,  0.05174977,  1.47767338,
         -0.38524091, -0.93645234]],

       [[-0.64138398, -2.0899181 , -1.29140263,  0.96852732,
          0.14364601,  0.15692115,  2.43493555,  0.81387378,
         -0.74431328, -0.5454011 ],
        [ 0.6297736 ,  0.93588396, -0.59121266,  0

## Concatenating

![](./concat.jpg)

In [70]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]]).T
np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [75]:
array1 = np.array(np.arange(1,25)).reshape((2,3,4))
print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [76]:
array2 = np.array(np.arange(1,13)).reshape((2,3,2))
print(array2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [77]:
array2.shape

(2, 3, 2)

In [78]:
np.concatenate((array1, array2), axis=2)

array([[[ 1,  2,  3,  4,  1,  2],
        [ 5,  6,  7,  8,  3,  4],
        [ 9, 10, 11, 12,  5,  6]],

       [[13, 14, 15, 16,  7,  8],
        [17, 18, 19, 20,  9, 10],
        [21, 22, 23, 24, 11, 12]]])

## Sorting

In [79]:
a = np.array([[1,4],[3,1]])
a

array([[1, 4],
       [3, 1]])

In [80]:
np.sort(a)

array([[1, 4],
       [1, 3]])

In [81]:
np.sort(a, axis=None)

array([1, 1, 3, 4])

In [82]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [83]:
a = np.array(np.random.randint(1, 100, 18)).reshape(2,3, -1)
a

array([[[38, 63, 39],
        [73, 94, 46],
        [65, 14, 18]],

       [[98, 55, 65],
        [56, 68, 17],
        [32, 43, 55]]])

In [84]:
print(a.shape)
np.sort(a, axis=0)

(2, 3, 3)


array([[[38, 55, 39],
        [56, 68, 17],
        [32, 14, 18]],

       [[98, 63, 65],
        [73, 94, 46],
        [65, 43, 55]]])

In [85]:
print(a.shape)
np.sort(a, axis=1)

(2, 3, 3)


array([[[38, 14, 18],
        [65, 63, 39],
        [73, 94, 46]],

       [[32, 43, 17],
        [56, 55, 55],
        [98, 68, 65]]])

In [86]:
print(a.shape)
np.sort(a, axis=2)

(2, 3, 3)


array([[[38, 39, 63],
        [46, 73, 94],
        [14, 18, 65]],

       [[55, 65, 98],
        [17, 56, 68],
        [32, 43, 55]]])

## Math functions

In [87]:
a

array([[[38, 63, 39],
        [73, 94, 46],
        [65, 14, 18]],

       [[98, 55, 65],
        [56, 68, 17],
        [32, 43, 55]]])

In [88]:
np.max(a)

98

In [89]:
np.maximum(a[0], a[1])

array([[98, 63, 65],
       [73, 94, 46],
       [65, 43, 55]])

In [90]:
np.min(a)

14

In [91]:
np.minimum(a[0], a[1])

array([[38, 55, 39],
       [56, 68, 17],
       [32, 14, 18]])

In [92]:
np.sum(a)

939

In [93]:
a

array([[[38, 63, 39],
        [73, 94, 46],
        [65, 14, 18]],

       [[98, 55, 65],
        [56, 68, 17],
        [32, 43, 55]]])

In [94]:
np.sum(a, axis=0)

array([[136, 118, 104],
       [129, 162,  63],
       [ 97,  57,  73]])

In [95]:
np.sum(a, axis=1)

array([[176, 171, 103],
       [186, 166, 137]])

In [96]:
np.sum(a, axis=2)

array([[140, 213,  97],
       [218, 141, 130]])

In [97]:
a

array([[[38, 63, 39],
        [73, 94, 46],
        [65, 14, 18]],

       [[98, 55, 65],
        [56, 68, 17],
        [32, 43, 55]]])

In [98]:
np.multiply(a[0], a[1])

array([[3724, 3465, 2535],
       [4088, 6392,  782],
       [2080,  602,  990]])

### Multiplication

#### Dot Product

In [99]:
# Returns the dot product of a and b. 
# If a and b are both scalars or both 1-D arrays then a scalar is returned; otherwise an array is returned
np.dot(a[0], a[1])

array([[ 8500,  8051,  5686],
       [13890, 12385,  8873],
       [ 7730,  5301,  5453]])

In [100]:
# perform matrix multiplication in NumPy
np.matmul(a[0], a[1])

array([[ 8500,  8051,  5686],
       [13890, 12385,  8873],
       [ 7730,  5301,  5453]])

#### Other functions

In [101]:
# Reverse the order of elements along axis 1 (left/right). 
# For a 2-D array, this flips the entries in each row in the left/right direction.
np.fliplr(np.matmul(a[0], a[1]))

array([[ 5686,  8051,  8500],
       [ 8873, 12385, 13890],
       [ 5453,  5301,  7730]])

In [102]:
# transpose of the matrix
np.matmul(a[0], a[1]).T

array([[ 8500, 13890,  7730],
       [ 8051, 12385,  5301],
       [ 5686,  8873,  5453]])

In [103]:
# find a diagonal element from a given matrix and gives output as one dimensional matrix
np.diagonal(np.matmul(a[0], a[1]))

array([ 8500, 12385,  5453])

In [104]:
np.diagonal(np.fliplr(np.matmul(a[0], a[1])))

array([ 5686, 12385,  7730])

In [105]:
# Return a numpy array of given shape and type, filled with ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
# Return a numpy array of given shape and type, filled with zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])